### ISSUE TITLE
Error on Android

### ISSUE THREAD

**Issue by jmuchaxo** [firebase/firebase-token-generator-java#11]
Using the library on android causes a runtime error, It is due to the fact that the commons-codec old version 1.4 is provided with Android and does not have encodeBase64URLSafeString .
...
 E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NoSuchMethodError: org.apache.commons.codec.binary.Base64.encodeBase64URLSafeString
            at com.firebase.security.token.JWTEncoder.encodeJson(JWTEncoder.java:64)

I am compiling with this on gradle build
compile 'com.firebase:firebase-token-generator:2.0.0'

**Comment by mikelehen** [comment]
Sorry for side-stepping your report, but can I ask why you are trying to use it on Android?  It's worth keeping in mind that because token generation requires your Firebase Secret, you should only generate tokens on trusted servers. You shouldn't embed your Firebase Secret directly into your application.

So generally speaking, it probably doesn't make sense to use firebase-token-generator-java from android.

**Comment by jmuchaxo** [comment]
I am doing  hybrid app, using twitter digits on Android for phone number based login , in general I need logon in Android but also on Webview for html based chat system done using firebase that has several login options such as firebase custom login.
I use the chat web app not pnly on android but also on desktop and other mobiles. 
I am improving from a solution on wich the Jwt token was generated with php but then is easier to find the http link to the script and someone being able to generate the token , its harder to reverse enginer the app to find the fb secret .
what other solution you suggest for an hybrid android app ?

**Comment by mikelehen** [comment]
Take a look at this thread on our google group: https://groups.google.com/forum/#!searchin/firebase-talk/digits/firebase-talk/sB7lPuyCVBQ/bgPdA0wsoUQJ

I believe once you've authed with Digits and gotten the auth token and token secret, you can use that to login to Firebase using twitter by calling authWithOAuthToken().  See https://www.firebase.com/docs/android/guide/login/twitter.html for more details.
